apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-tracking-server
  labels:
      app: mlflow-tracking-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-tracking-server-pods
  template:
    metadata:
      labels:
        app: mlflow-tracking-server-pods
    spec:
      containers:
        - name: mlflow-tracking-server-pod
          image: wcaicedo/mlflow-tracking-server:latest
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: 1Gi
              cpu: "2"
            requests:
              memory: 1Gi
              cpu: "1"
          imagePullPolicy: Always
          env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mlflow-postgresql-credentials
                key: postgresql-password
          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: mlflow-configmap
                key: DB_USERNAME
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: mlflow-configmap
                key: DB_HOST
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: mlflow-configmap
                key: DB_NAME
          - name: DEFAULT_ARTIFACT_ROOT
            valueFrom:
              configMapKeyRef:
                name: mlflow-configmap
                key: DEFAULT_ARTIFACT_ROOT
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mlflow-tracking-server
  name: mlflow-tracking-server
spec:
  selector:
    app: mlflow-tracking-server-pods
  type: NodePort
  ports:
    - name: http
      nodePort: 30036
      port: 5000
      protocol: TCP
      targetPort: 5000

# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: mlflow-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   ingressClassName: nginx
#   rules:
#   - http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: mlflow-tracking-server
#             port:
#               number: 5000
